### ISSUE TITLE
Transfer Any Trademarks

### ISSUE THREAD

**Issue by kflansburg** [krator-rs/krator#20]
Transfer any trademark and logo mark assets over to the LF - https://github.com/cncf/foundation/tree/master/agreements has agreements.

**Comment by kflansburg** [comment]
I don't believe there are any for Krator, but someone from Microsoft should probably confirm.

**Comment by thomastaylor312** [comment]
As far as I know we don't have any trademarks or logos for Krustlet to transfer, so we should be good here. I'll mark this as complete
