### ISSUE TITLE
Design document?

### ISSUE THREAD

**Issue by vsoch** [krator-rs/krator#76]
Hiya! I was interested to learn about state machines (and in the context of rust) and found your project. I usually read code to understand how things work, but I'm not great with rust and was wondering if you had any design diagrams or similar somewhere, and that could help me read the code. Thanks!

**Comment by kflansburg** [comment]
Hey there, I'm not sure if I have any design diagrams anymore, but there were two KubeCon talks that touch on this: 
- [Leveraging State Machines to Build Operators in Rust](https://www.youtube.com/watch?v=2YSdRpCnG-U)
- [Kubelet Deep Dive: Writing a Kubelet in Rust](https://www.youtube.com/watch?v=idMf865wwD8)


Just a heads up, this project is mostly abandoned and about to be archived by CNCF.

**Comment by vsoch** [comment]
Thank you for sharing these! I'm sorry it's abandoned / about to be archived, it's really cool work. I minimally appreciate it for the learning.
